[package]
name = "electrumx_client"
version = "0.1.2"
authors = ["evgeniy.scherbina <evgeniy.scherbina@bitfury.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
bitcoin = { version = "0.25", features = [ "use-serde" ] }
hex = "0.3.2"
sha2 = "0.8.0"
clap = "2.33.3"
